version: '3.2'

volumes:
  db-data:

services:
  frontend:
    container_name: shag-313-frontend
    build:
      context: .
      dockerfile: .deploy/docker/frontend/Dockerfile
    volumes:
      - ./.deploy/docker/frontend/nginx.conf:/etc/nginx/conf.d/default.conf
      - .:/app
    depends_on:
      - backend
    ports:
      - 8047:80

  backend:
    container_name: shag-313-backend
    build:
      context: .
      dockerfile: .deploy/docker/backend/Dockerfile
    volumes:
      - .:/app

  db:
    container_name: shag-313-db
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_DB: app
    volumes:
      - db-data:/var/lib/postgresql/data

  redis:
    container_name: shag-313-redis
    image: redis
